language: csharp
solution: dotnet-enlight-sdk.sln

mono: none
dotnet: 2.0

install: dotnet restore

script:
  - dotnet build --configuration Release --no-restore --verbosity n
  - dotnet pack --configuration Release --no-build --no-restore --verbosity n /p:Version="$TRAVIS_TAG"

deploy:
  provider: script
  script: true # TODO dotnet nuget push -k <key> -s <source> Enlight/bin/Release/SKF.Enlight.*.nupkg
  on:
    branch: master
    tags: true

