// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Hierarchy.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace SKF.Enlight.ProtocolBuffers {
  public static partial class Hierarchy
  {
    static readonly string __ServiceName = "grpcapi.Hierarchy";

    static readonly grpc::Marshaller<global::SKF.Enlight.ProtocolBuffers.Void> __Marshaller_Void = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SKF.Enlight.ProtocolBuffers.Void.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SKF.Enlight.ProtocolBuffers.String> __Marshaller_String = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SKF.Enlight.ProtocolBuffers.String.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SKF.Enlight.ProtocolBuffers.Node> __Marshaller_Node = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SKF.Enlight.ProtocolBuffers.Node.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SKF.Enlight.ProtocolBuffers.Nodes> __Marshaller_Nodes = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SKF.Enlight.ProtocolBuffers.Nodes.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SKF.Enlight.ProtocolBuffers.SaveNodeInput> __Marshaller_SaveNodeInput = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SKF.Enlight.ProtocolBuffers.SaveNodeInput.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SKF.Enlight.ProtocolBuffers.DeleteNodeInput> __Marshaller_DeleteNodeInput = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SKF.Enlight.ProtocolBuffers.DeleteNodeInput.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SKF.Enlight.ProtocolBuffers.Bytes> __Marshaller_Bytes = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SKF.Enlight.ProtocolBuffers.Bytes.Parser.ParseFrom);

    static readonly grpc::Method<global::SKF.Enlight.ProtocolBuffers.Void, global::SKF.Enlight.ProtocolBuffers.String> __Method_DeepPing = new grpc::Method<global::SKF.Enlight.ProtocolBuffers.Void, global::SKF.Enlight.ProtocolBuffers.String>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeepPing",
        __Marshaller_Void,
        __Marshaller_String);

    static readonly grpc::Method<global::SKF.Enlight.ProtocolBuffers.String, global::SKF.Enlight.ProtocolBuffers.Node> __Method_GetNode = new grpc::Method<global::SKF.Enlight.ProtocolBuffers.String, global::SKF.Enlight.ProtocolBuffers.Node>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetNode",
        __Marshaller_String,
        __Marshaller_Node);

    static readonly grpc::Method<global::SKF.Enlight.ProtocolBuffers.String, global::SKF.Enlight.ProtocolBuffers.Nodes> __Method_GetNodes = new grpc::Method<global::SKF.Enlight.ProtocolBuffers.String, global::SKF.Enlight.ProtocolBuffers.Nodes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetNodes",
        __Marshaller_String,
        __Marshaller_Nodes);

    static readonly grpc::Method<global::SKF.Enlight.ProtocolBuffers.SaveNodeInput, global::SKF.Enlight.ProtocolBuffers.String> __Method_SaveNode = new grpc::Method<global::SKF.Enlight.ProtocolBuffers.SaveNodeInput, global::SKF.Enlight.ProtocolBuffers.String>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveNode",
        __Marshaller_SaveNodeInput,
        __Marshaller_String);

    static readonly grpc::Method<global::SKF.Enlight.ProtocolBuffers.DeleteNodeInput, global::SKF.Enlight.ProtocolBuffers.Void> __Method_DeleteNode = new grpc::Method<global::SKF.Enlight.ProtocolBuffers.DeleteNodeInput, global::SKF.Enlight.ProtocolBuffers.Void>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteNode",
        __Marshaller_DeleteNodeInput,
        __Marshaller_Void);

    static readonly grpc::Method<global::SKF.Enlight.ProtocolBuffers.Void, global::SKF.Enlight.ProtocolBuffers.Bytes> __Method_GetEventStream = new grpc::Method<global::SKF.Enlight.ProtocolBuffers.Void, global::SKF.Enlight.ProtocolBuffers.Bytes>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetEventStream",
        __Marshaller_Void,
        __Marshaller_Bytes);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SKF.Enlight.ProtocolBuffers.HierarchyReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Hierarchy</summary>
    public abstract partial class HierarchyBase
    {
      public virtual global::System.Threading.Tasks.Task<global::SKF.Enlight.ProtocolBuffers.String> DeepPing(global::SKF.Enlight.ProtocolBuffers.Void request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SKF.Enlight.ProtocolBuffers.Node> GetNode(global::SKF.Enlight.ProtocolBuffers.String request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SKF.Enlight.ProtocolBuffers.Nodes> GetNodes(global::SKF.Enlight.ProtocolBuffers.String request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SKF.Enlight.ProtocolBuffers.String> SaveNode(global::SKF.Enlight.ProtocolBuffers.SaveNodeInput request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SKF.Enlight.ProtocolBuffers.Void> DeleteNode(global::SKF.Enlight.ProtocolBuffers.DeleteNodeInput request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task GetEventStream(global::SKF.Enlight.ProtocolBuffers.Void request, grpc::IServerStreamWriter<global::SKF.Enlight.ProtocolBuffers.Bytes> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Hierarchy</summary>
    public partial class HierarchyClient : grpc::ClientBase<HierarchyClient>
    {
      /// <summary>Creates a new client for Hierarchy</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public HierarchyClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Hierarchy that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public HierarchyClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected HierarchyClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected HierarchyClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::SKF.Enlight.ProtocolBuffers.String DeepPing(global::SKF.Enlight.ProtocolBuffers.Void request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeepPing(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SKF.Enlight.ProtocolBuffers.String DeepPing(global::SKF.Enlight.ProtocolBuffers.Void request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeepPing, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SKF.Enlight.ProtocolBuffers.String> DeepPingAsync(global::SKF.Enlight.ProtocolBuffers.Void request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeepPingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SKF.Enlight.ProtocolBuffers.String> DeepPingAsync(global::SKF.Enlight.ProtocolBuffers.Void request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeepPing, null, options, request);
      }
      public virtual global::SKF.Enlight.ProtocolBuffers.Node GetNode(global::SKF.Enlight.ProtocolBuffers.String request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetNode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SKF.Enlight.ProtocolBuffers.Node GetNode(global::SKF.Enlight.ProtocolBuffers.String request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetNode, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SKF.Enlight.ProtocolBuffers.Node> GetNodeAsync(global::SKF.Enlight.ProtocolBuffers.String request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetNodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SKF.Enlight.ProtocolBuffers.Node> GetNodeAsync(global::SKF.Enlight.ProtocolBuffers.String request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetNode, null, options, request);
      }
      public virtual global::SKF.Enlight.ProtocolBuffers.Nodes GetNodes(global::SKF.Enlight.ProtocolBuffers.String request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetNodes(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SKF.Enlight.ProtocolBuffers.Nodes GetNodes(global::SKF.Enlight.ProtocolBuffers.String request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetNodes, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SKF.Enlight.ProtocolBuffers.Nodes> GetNodesAsync(global::SKF.Enlight.ProtocolBuffers.String request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetNodesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SKF.Enlight.ProtocolBuffers.Nodes> GetNodesAsync(global::SKF.Enlight.ProtocolBuffers.String request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetNodes, null, options, request);
      }
      public virtual global::SKF.Enlight.ProtocolBuffers.String SaveNode(global::SKF.Enlight.ProtocolBuffers.SaveNodeInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveNode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SKF.Enlight.ProtocolBuffers.String SaveNode(global::SKF.Enlight.ProtocolBuffers.SaveNodeInput request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SaveNode, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SKF.Enlight.ProtocolBuffers.String> SaveNodeAsync(global::SKF.Enlight.ProtocolBuffers.SaveNodeInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveNodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SKF.Enlight.ProtocolBuffers.String> SaveNodeAsync(global::SKF.Enlight.ProtocolBuffers.SaveNodeInput request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SaveNode, null, options, request);
      }
      public virtual global::SKF.Enlight.ProtocolBuffers.Void DeleteNode(global::SKF.Enlight.ProtocolBuffers.DeleteNodeInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteNode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SKF.Enlight.ProtocolBuffers.Void DeleteNode(global::SKF.Enlight.ProtocolBuffers.DeleteNodeInput request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteNode, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SKF.Enlight.ProtocolBuffers.Void> DeleteNodeAsync(global::SKF.Enlight.ProtocolBuffers.DeleteNodeInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteNodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SKF.Enlight.ProtocolBuffers.Void> DeleteNodeAsync(global::SKF.Enlight.ProtocolBuffers.DeleteNodeInput request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteNode, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::SKF.Enlight.ProtocolBuffers.Bytes> GetEventStream(global::SKF.Enlight.ProtocolBuffers.Void request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetEventStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::SKF.Enlight.ProtocolBuffers.Bytes> GetEventStream(global::SKF.Enlight.ProtocolBuffers.Void request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetEventStream, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override HierarchyClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HierarchyClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(HierarchyBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_DeepPing, serviceImpl.DeepPing)
          .AddMethod(__Method_GetNode, serviceImpl.GetNode)
          .AddMethod(__Method_GetNodes, serviceImpl.GetNodes)
          .AddMethod(__Method_SaveNode, serviceImpl.SaveNode)
          .AddMethod(__Method_DeleteNode, serviceImpl.DeleteNode)
          .AddMethod(__Method_GetEventStream, serviceImpl.GetEventStream).Build();
    }

  }
}
#endregion
